# Generated by Django 3.2.12 on 2022-02-05 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports', models.CharField(choices=[('Basketball', 'Basketball'), ('Baseball', 'Baseball'), ('Ice Hockey', 'Ice Hockey'), ('Football', 'Football')], default='Basketball', max_length=255)),
                ('league', models.CharField(choices=[('NBA', 'NBA'), ('MLB', 'MLB'), ('NHL', 'NHL'), ('NFL', 'NFL')], default='NBA', max_length=255)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('startTime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updateTime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('awayName', models.CharField(blank=True, max_length=255, null=True)),
                ('homeName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('odds', models.FloatField(default=1)),
                ('oddsAmerican', models.FloatField(default=1)),
                ('line', models.IntegerField(default=0)),
                ('self_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('updateTime', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_market_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('market_type', models.CharField(choices=[('Spread', 'Spread'), ('Total', 'Total Points'), ('Money', 'Money line'), ('Alternative Spreads', 'Alternative Spreads')], default='Spread', max_length=255)),
                ('selection', models.ManyToManyField(blank=True, to='api.Selection')),
            ],
        ),
        migrations.CreateModel(
            name='BookieEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_event_id', models.CharField(max_length=255)),
                ('bookie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='api.bookie')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookies', to='api.event')),
                ('market', models.ManyToManyField(blank=True, to='api.Market')),
            ],
        ),
    ]
