# Generated by Django 3.2.12 on 2022-02-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_e_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookieevent',
            name='market',
        ),
        migrations.AddField(
            model_name='market',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.bookieevent'),
        ),
        migrations.AlterField(
            model_name='bookieevent',
            name='bookie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.bookie'),
        ),
        migrations.AlterField(
            model_name='bookieevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookies', to='api.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='e_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
