# Generated by Django 3.2.12 on 2022-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220205_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookieevent',
            name='bookie',
            field=models.CharField(choices=[('Draft Kings', 'Draft Kings'), ('Fanduel', 'Fanduel'), ('TwinSpires', 'TwinSpires')], default='TwinSpires', max_length=255),
        ),
        migrations.DeleteModel(
            name='Bookie',
        ),
    ]
