# Generated by Django 3.2.12 on 2022-02-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220205_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookieevent',
            name='self_event_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
