# Generated by Django 3.2.12 on 2022-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_bookieevent_self_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='english_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
