# Generated by Django 3.2.12 on 2022-02-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event_english_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='self_id',
            new_name='self_selection_id',
        ),
        migrations.AlterField(
            model_name='bookieevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='api.event'),
        ),
    ]
