# Generated by Django 3.2.12 on 2022-02-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220207_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='event',
        ),
        migrations.AddField(
            model_name='market',
            name='self_event_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='line',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='odds',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='oddsAmerican',
            field=models.FloatField(default=1, null=True),
        ),
    ]
