# Generated by Django 3.2.12 on 2022-02-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220207_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='market_type',
            field=models.CharField(choices=[('Spread', 'Spread'), ('Total', 'Total Points'), ('Money Line', 'Money line'), ('Alternative Spreads', 'Alternative Spreads')], default='Spread', max_length=255),
        ),
    ]
