# Generated by Django 3.2.12 on 2022-02-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_selection_self_market_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='self_event_id',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
