# Generated by Django 3.2.12 on 2022-02-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_selection_self_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='awayName',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='english_name',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='homeName',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='league',
            field=models.CharField(choices=[('NBA', 'NBA'), ('MLB', 'MLB'), ('NHL', 'NHL'), ('NFL', 'NFL')], db_index=True, default='NBA', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='sports',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Baseball', 'Baseball'), ('Ice Hockey', 'Ice Hockey'), ('Football', 'Football')], db_index=True, default='Basketball', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='updateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selection',
            name='updateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
